Repository TrungDuc9998/Front-end_Kinglap, pull requests merged in 2022-11, with the labels that each got.

#42 Duc nt order
  src/pages/Order/Table.js
Labels: code done

#51 tung_update loadData table order vs orderdetail
  src/pages/Order/Order.js
Labels: review design

#57 Son_update_Order_10/11
  package-lock.json
  src/components/layout/DefaultLayout/index.js
  src/pages/Order/CancelOrder.js
  src/pages/Order/ConfirmOrder.js
  src/pages/Order/OrderDelivering.js
  src/pages/Order/OrderSuccess.js
  src/pages/Order/OrderWait.js
Labels: review design

#60 hieu_fix_cart
  src/pages/customer/Cart.js
  src/pages/customer/HomeUser.js
  src/store/reducer.js
Labels: code done

#70 tung_filter_order
  src/pages/Order/Order.js
  src/pages/Order/order.css
Labels: review design

#41 son_update_01/11
  src/pages/Discount/index.js
Labels: code done, review design

#71 hieu_createProduct
  src/pages/Product/CreateProduct.js
Labels: code done

#80 fix bug phan quyen
  src/components/users/menu.js
  src/pages/customer/Cart.js
  src/pages/customer/HomeUser.js
Labels: bug

#82 tung xuat pdf order
  package-lock.json
  package.json
  src/pages/Order/Order.js
  src/pages/Order/order.css
Labels: review design

#92 fontend dang ky, user
  src/components/users/Login.js
Labels: code done

#95 Son_Update_DiscountProduct_Price_23/11
  src/pages/Discount/index.js
Labels: review design
